# Delegates to build/makefile

all: server client
	$(MAKE) -C build all

server:
	$(MAKE) -C build server

client:
	$(MAKE) -C build client

clean:
	$(MAKE) -C build clean

.PHONY: all server client clean
